### ISSUE TITLE
Add Logging for missing CompleteScreen texture

### ISSUE THREAD

**Issue by coloursofnoise** [EverestAPI/Everest#347]
Missing CompleteScreen textures should be logged for easier debugging[[1]](https://github.com/EverestAPI/Everest/blob/4f889db4f97ce92c25af5b0f580a963c51a5f271/Celeste.Mod.mm/Patches/CompleteRenderer.cs#L121)

**Comment by caeyo** [comment]
@coloursofnoise any preferences for the log message? My current idea is this:

- meta.yaml:
```
CompleteScreen:
    Atlas: "Endscreens/caeyo_test"
    Start: [ 0.0, 0.0 ]
    Center: [ 0.0, 0.0 ]
    Offset: [ 0.0, 0.0 ]
    Layers:
      - Type: "layer"
        Images: [ "static" ]
        Position: [ 0.0, 0.0 ]
        Scroll: [ 0.0 ]
```

- Log line:
```
(05/11/2022 17:31:12) [Everest] [Warn] [CompleteScreenRenderer] Failed to find Image "static" in Atlas "Endscreens/caeyo_test"
```

I thought it'd be good to include the Atlas path along with the Image name for easier debugging in the case of a mistake in the path, but let me know if that's unnecessary. The Atlas path is retrieved via [GetDataPath](https://github.com/EverestAPI/Everest/blob/d5233e52a1b52f2906db12ea868ede7890007349/Celeste.Mod.mm/Patches/Monocle/Atlas.cs#L487), and I just took off the `Graphics\Atlases\` part of the return string to better match the yaml for clarity (assuming there can't be a situation where there are any other characters before the `Endscreens` part of the path)
