### ISSUE TITLE
the DLL line in everest.yaml being a nonexistent file is silently ignored

### ISSUE THREAD

**Issue by microlith57** [EverestAPI/Everest#522]
everest `3606-azure-49aab`
see https://gamebanana.com/mods/download/320381#FileInfo_724149 as of 15/09/2022; this mod has
```yaml
- Name: ParrotHelper
  Version: 1.0.1
  DLL: bin/Debug/ParrotHelper.dll
  Dependencies:
    - Name: Everest
      Version: 1.2792.0
```
but there is no `bin` folder in the zip, so the assembly is not loaded.
i would expect such an error to result in either a crash or a log warning, but instead it is silently ignored.

see also:
https://github.com/EverestAPI/Everest/blob/47e54f69e7bdda4f7e96c2897205dd5ca6569997/Celeste.Mod.mm/Mod/Everest/Everest.cs#L383
