### ISSUE TITLE
Allow extracting arbitrary files to Mods/Cache

### ISSUE THREAD

**Issue by swoolcock** [EverestAPI/Everest#627]
### I am planning on implementing this myself

Yes

### Describe your request

I'm currently developing a helper for Everest Core that's a wrapper on DearImGui, and I have everything working apart from automatically loading native libs.

Manually dumping the native libs into `Mods/Cache` allows Everest to load them just fine, but there's no way for my helper to put them there short of manually extracting them from the mod zip at mod initialisation.

I believe a cleaner way to do this would be to allow mod authors to explicitly list off additional files in the zip that should be extracted to `Mods/Cache`.  I think it makes sense for this to go directly into everest.yaml.

```yaml
- Name: YourModName
  Version: ...
  DLL: ...
  Resources:
    - imgui.dylib
    - imgui.so
    - ...
  Dependencies:
    - Name: Everest
      Version: 1.0.0
  OptionalDependencies:
    - Name: ...
      Version: ...
```
